version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017
      - DB_NAME=user_aplication
      - SECRET_KEY=7uf=6nw4n+5%vbcrs+^w6p_ocj3!o4w&-5n3t-ym$6!^vi3$1k76zl&@f1^a6$f1r9o9s2o4&8@
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_MINUTES=3800
      - ALGORITHM=HS256
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TIME_CHASH_OTP=360
      - OTP_APIKEY=OWU1NTljM2EtNjhlNy00OTk1LTk5NDItMDlkNjIxMDQ0MjMzODliZDE0NDlmMTU5MmFjYTEzYTA0MTE2YTNhMTY0OTU=
      - OTP_PATTERN_CODE=dkkyp5kuqnkzdba
      - OTP_PHONE=+983000505
      - OTP_UTL=https://api2.ippanel.com/api/v1/sms/pattern/normal/send
      - STATIC_PATH=http://web:8000/
      - STATIC_DIR=static/media
    volumes:
      - ./volume/app:/usr/src/app/
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volume/db:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#services:
#
#  mongodb:
#    image: mongo:latest
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - /home/hamid/Desktop/New Folder (1)/db:/data/db
#
#  redis:
#    image: redis:alpine
#    restart: always
#    ports:
#      - "6379:6379"
#    depends_on:
#    - mongodb
#
#  web:
#    build: .
#    command: /bin/sh -c "wait-for-it mongodb:27017 -- uvicorn --reload --workers 10 main:app"
#    volumes:
#      - /home/hamid/Desktop/LLM1/New Folder/:/usr/src/app/
#    ports:
#      - 8000:8000
#    depends_on:
#      - mongodb
#      - redis
